# Generated by Django 4.0.4 on 2022-07-16 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='Imgs/Faculty')),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('qualf_pic', models.FileField(blank=True, null=True, upload_to='Docs/Faculty')),
                ('experties_1', models.CharField(blank=True, max_length=20, null=True)),
                ('experties_2', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_type', models.CharField(max_length=20)),
                ('doc_num', models.CharField(max_length=20)),
                ('doc_pic', models.FileField(blank=True, null=True, upload_to='Docs/Faculty')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
