# Generated by Django 4.0.4 on 2022-07-16 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        ('faculty', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('fee', models.CharField(blank=True, max_length=20, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='Imgs/Superuser')),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('lectures', models.CharField(blank=True, max_length=20, null=True)),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('srt_desc', models.CharField(max_length=100)),
                ('lng_desc', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('enrolled_std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='Imgs/Superuser')),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('designation', models.CharField(blank=True, max_length=70, null=True)),
                ('occupation', models.CharField(blank=True, max_length=70, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrsLrn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn_nm', models.TextField(blank=True, null=True)),
                ('lrn_dsc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.course')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timing', models.TimeField()),
                ('start_dt', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('student', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
